import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { AzureBlobFileStore } from "./storage-azure";

/**
 * Write-once storage for frozen versions and comment snapshots. Keys are generated by the
 * app and never overwritten, so a stored version can be proven identical later by its hash.
 */
export interface FileStore {
  put(key: string, bytes: Uint8Array, contentType: string): Promise<void>;
  get(key: string): Promise<Uint8Array>;
}

/** Development store on local disk. Production uses Azure Blob in the college's tenant. */
class LocalFileStore implements FileStore {
  constructor(private root: string) {}

  private resolve(key: string) {
    const full = path.resolve(this.root, key);
    if (!full.startsWith(path.resolve(this.root) + path.sep)) throw new Error("Invalid storage key");
    return full;
  }

  async put(key: string, bytes: Uint8Array) {
    const full = this.resolve(key);
    await mkdir(path.dirname(full), { recursive: true });
    await writeFile(full, bytes, { flag: "wx" }); // fail rather than overwrite
  }

  async get(key: string) {
    return new Uint8Array(await readFile(this.resolve(key)));
  }
}

let store: FileStore | undefined;

export function getFileStore(): FileStore {
  if (!store) {
    const blobUrl = process.env.AZURE_BLOB_ACCOUNT_URL;
    if (blobUrl) {
      store = new AzureBlobFileStore(blobUrl, process.env.AZURE_BLOB_CONTAINER ?? "letters");
    } else {
      if (process.env.NODE_ENV === "production" && !process.env.STORAGE_DIR)
        throw new Error("Configure file storage for production");
      store = new LocalFileStore(process.env.STORAGE_DIR ?? path.resolve(process.cwd(), ".storage"));
    }
  }
  return store;
}

export function setFileStore(s: FileStore | undefined) {
  store = s;
}

export function sha256(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}
